USWDS-Compile - Dependencies: GulpJS v5
uswds/uswds-compile pull request #96
Opened 2024-04-05 20:14 UTC by mejiaj

TK

2024-06-21 14:06 UTC, amyleadem requested changes
- [x] Confirmed that I could successfully perform all the gulp tasks in the uswds-sandbox test branch
- [ ] Confirmed that I could successfully perform gulp tasks after installing on uswds-site
    - When I [installed this branch on uswds-site](https://github.com/uswds/uswds-site/pull/2719), I noticed that the fonts no longer rendered correctly (See screenshot below). When I tested reverting the branch to version ^1.1.0, the fonts rendered correctly again. 
    ![image](https://github.com/uswds/uswds-compile/assets/93996430/6d4cba9c-8077-4813-a6ab-4b2d9990499e)
    - Also, noting that to get the gulp `watchSass` task to run without error, I needed to remove gulp 4 from the package.json in the uswds-site repo.
- [x] Confirmed the vulnerabilities listed in the PR description are accurate and up-to-date

## Follow-up tasks
The documentation  on the [Phase 2: Compile](https://designsystem.digital.gov/documentation/getting-started/developers/phase-two-compile/) page specifically mentions to tool using Gulp 4. We should be sure to update that after this PR is merged.

2024-07-01 17:01 UTC, mahoneycm commented
Confirming that I'm seeing similar compilation errors in both Sandbox and Site surrounding image and font compilation.

## Img compilation error

Banner missing American flag icon

Various img’s in assets folder are failing to load/compile:

- circle-124.png
- hero.jpg
- hero.webp
- logo-img
- us_flag_small.png

Looks like all other nested images are compiling fine, just a few in the root assets folder are missing.

## Font compilation error

Console errors

<img width="532" alt="image" src="https://github.com/uswds/uswds-compile/assets/25211650/99abe6d7-5179-4458-a2fc-4754b7d065c6">

Installing Gulp5 on Site reduces the number of errors but I see the same results on the page.
<img width="318" alt="image" src="https://github.com/uswds/uswds-compile/assets/25211650/181c58fe-4986-44fb-a368-400776ea5dde">


Trying to open the fonts files in VS code gives the following error:

> The file is not displayed in the text editor because it is either binary or uses an unsupported text encoding.
>

2024-07-01 21:33 UTC, mejiaj commented on gulpfile.js
> +    encoding: false
> [!NOTE]  
> Didn't notice any difference here. Keeping because SVGs it still following recommendation for removing encoding from images.

2024-07-01 21:42 UTC, mejiaj commented
I was able to confirm the following issues:

- [x] Fonts corrupt/not rendering
- [x] Images corrupt/not rendering
- [ ] Icon regressions [test page](https://federalist-d5e7c07c-6ffa-4b8e-935f-49a7df24a505.sites.pages.cloud.gov/preview/uswds/uswds-sandbox/jm-test-compile-gulp5/)

Any help reproducing icon issue would be appreciated.

CC @amyleadem @mahoneycm

2024-07-02 13:42 UTC, mejiaj commented on gulpfile.js
> +    }).pipe(dest(paths.dist.fonts));
Avoids corruption on images and fonts.

More info here: https://github.com/gulpjs/gulp/issues/2803

2024-07-02 15:23 UTC, mahoneycm approved these changes
This is looking great! 

- [x] Previous Sandbox regressions resolved
- [x] Previous Site regressions resolved
- [x] Scripts run without error
- [x] Update resolves a high severity dependency vulnerability

Also noting that I never observed any icon regression that you mentioned being unable to reproduce. All the img regressions I saw were specifically jpg, png, or webp files specifically in the `/assets/img/` directory which have since been resolved 👍

2024-07-02 21:02 UTC, amyleadem approved these changes
Looks good to me! Thanks for your work on this. 👏 

In both uswds-site and uswds-sandbox test branches, I was able to confirm:
- [x]  Fonts appear to render correctly
- [x]  Images appear to render correctly
- [x]  No console errors
- [x]  Able to successfully run gulp tasks

Also:
- [x]  Confirm `return src()` calls in gulpfile.js turn off encoding for images and fonts (thanks for the [helpful note](https://github.com/uswds/uswds-compile/pull/96/files#r1662556043), @mejiaj!)

2024-07-10 13:41 UTC, heymatthenry approved these changes
LGTM 🚀

2024-07-15 15:42 UTC, merged

2024-07-19 17:02 UTC, mdmower-csnw commented
@mejiaj - Oooh, super important, critical, drop-everything-the-project-is-on-fire change still needs to be made along with this PR... the readme needs to change "Gulp 4" to "Gulp 5"!  😉

2024-07-19 17:51 UTC, angeliquejw commented
Is there a timeline for when these changes will also be pushed to the [package](https://www.npmjs.com/package/@uswds/compile)?

2024-07-19 18:25 UTC, annepetersen commented
(I don't have the best info to answer your question, but: hi @angeliquejw! good to "see" you 👋)